#!/usr/bin/env bash
# Copyright (c) 2016 The UUV Simulator Authors.
# All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Only use this node if Gazebo is being using the a UUV Simulator world plugin
# for generation of current velocity topics
rosservice call /hydrodynamics/set_current_velocity_model "{mean: 0.6, min: 0.4, max: 0.8, noise: 0.01, mu: 0.05}"
rosservice call /hydrodynamics/set_current_horz_angle_model "{mean: 0.0, min: -0.8, max: 0.8, noise: 0.01, mu: 0.05}"
