#!/usr/bin/env bash
# Copyright (c) 2016 The UUV Simulator Authors.
# All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

rosservice call /plume/create_passive_scalar_turbulent_plume "turbulent_diffusion_coefficients: {x: 0.05, y: 0.05, z: 0.05}
source: {x: -0.0, y: 0.0, z: -40.0}
buoyancy_flux: 0.05
stability_param: 0.001
n_points: 100000
max_particles_per_iter: 10
x_min: -200.0
x_max: 200.0
y_min: -75.0
y_max: 75.0
z_min: -50.0
z_max: 0.0
max_life_time: -1"
