#!/usr/bin/env bash
# Copyright (c) 2016 The UUV Simulator Authors.
# All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Use the services below to start a current velocity topic using the
# current velocity server from uuv_plume_simulator's package

# For a quasi-constant current velocity use the service call below
# rosservice call set_current_velocity "{velocity: 0.2, horizontal_angle: 0.0}"

rosservice call /current_velocity_server/set_current_velocity_model "{mean: 0.2, min: 0.1, max: 0.3, noise: 0.002, mu: 0.01}"
rosservice call /current_velocity_server/set_angle_model "{mean: 0.2, min: 0.0, max: 0.8, noise: 0.02, mu: 0.1}"
